{% set version = '4.1-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hmisc
  version: {{ version|replace("-", "_") }}

source:
  fn: Hmisc_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/Hmisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Hmisc/Hmisc_{{ version }}.tar.gz
  sha256: 991db21cdf73ffbf5b0239a4876b2e76fd243ea33528afd88dc968792f281498

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-formula
    - r-acepack
    - r-base64enc
    - r-cluster
    - r-data.table
    - r-foreign
    - r-ggplot2 >=2.2
    - r-gridextra
    - r-gtable
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-lattice
    - r-latticeextra
    - r-nnet
    - r-rpart
    - r-survival >=2.40_1
    - r-viridis
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-formula
    - r-acepack
    - r-base64enc
    - r-cluster
    - r-data.table
    - r-foreign
    - r-ggplot2 >=2.2
    - r-gridextra
    - r-gtable
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-lattice
    - r-latticeextra
    - r-nnet
    - r-rpart
    - r-survival >=2.40_1
    - r-viridis

test:
  commands:
    - $R -e "library('Hmisc')"           # [not win]
    - "\"%R%\" -e \"library('Hmisc')\""  # [win]

about:
  home: http://biostat.mc.vanderbilt.edu/Hmisc, https://github.com/harrelfe/Hmisc
  license: GPL (>= 2)
  summary: Contains many functions useful for data analysis, high-level graphics, utility operations,
    functions for computing sample size and power, importing and annotating datasets,
    imputing missing values, advanced table making, variable clustering, character string
    manipulation, conversion of R objects to LaTeX and html code, and recoding variables.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
