{% set version = "5.1-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hmisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Hmisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Hmisc/Hmisc_{{ version }}.tar.gz
  sha256: 18507eb61d2473918161c232aff61491c028611cbed5ab947de8b4489f852078

build:
  merge_build_host: true  # [win]
  skip: true  # [ppc64le]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-cluster
    - r-colorspace
    - r-data.table
    - r-foreign
    - r-formula
    - r-ggplot2 >=2.2
    - r-gridextra
    - r-gtable
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-knitr
    - r-lattice
    - r-latticeextra
    - r-nnet
    - r-rmarkdown
    - r-rpart
    - r-survival >=3.1_6
    - r-viridis
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-base64enc
    - r-cluster
    - r-colorspace
    - r-data.table
    - r-foreign
    - r-formula
    - r-ggplot2 >=2.2
    - r-gridextra
    - r-gtable
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-knitr
    - r-lattice
    - r-latticeextra
    - r-nnet
    - r-rmarkdown
    - r-rpart
    - r-survival >=3.1_6
    - r-viridis

test:
  commands:
    - $R -e "library('Hmisc')"           # [not win]
    - "\"%R%\" -e \"library('Hmisc')\""  # [win]

about:
  home: https://hbiostat.org/R/Hmisc/
  dev_url: https://github.com/harrelfe/Hmisc
  license: GPL-2.0-or-later
  summary: Contains many functions useful for data analysis, high-level graphics, utility operations, functions for computing sample size and power, importing and annotating datasets, imputing missing values, advanced table making, variable clustering, character string manipulation, conversion of R objects to LaTeX and html
    code, and recoding variables.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
