{% set version = "5.1-3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-hmisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Hmisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Hmisc/Hmisc_{{ version }}.tar.gz
  sha256: 3c61772ff7a78ca5855189faa810c74117dc5df240103adc6e90eb94e9c605eb

build:
  skip: true  # [ppc64le]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-formula                  # [build_platform != target_platform]
    - r-knitr                    # [build_platform != target_platform]
    - r-rmarkdown                # [build_platform != target_platform]
    - r-gridextra                # [build_platform != target_platform]
    - r-viridis                  # [build_platform != target_platform]
    - r-ggplot2                  # [build_platform != target_platform]
    - r-cluster                  # [build_platform != target_platform]
    - r-gtable                   # [build_platform != target_platform]
    - r-htmltable                # [build_platform != target_platform]
    - r-htmltools                # [build_platform != target_platform]
    - r-foreign                  # [build_platform != target_platform]
    - r-data.table               # [build_platform != target_platform]
    - r-survival                 # [build_platform != target_platform]
    - r-lattice                  # [build_platform != target_platform]
    - r-nnet                     # [build_platform != target_platform]
    - r-latticeextra             # [build_platform != target_platform]
    - r-rpart                    # [build_platform != target_platform]
    - r-base64enc                # [build_platform != target_platform]
    - r-colorspace               # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-cluster
    - r-colorspace
    - r-data.table
    - r-foreign
    - r-formula
    - r-ggplot2 >=2.2
    - r-gridextra
    - r-gtable
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-knitr
    - r-lattice
    - r-latticeextra
    - r-nnet
    - r-rmarkdown
    - r-rpart
    - r-survival >=3.1_6
    - r-viridis
  run:
    - r-base
    - r-base64enc
    - r-cluster
    - r-colorspace
    - r-data.table
    - r-foreign
    - r-formula
    - r-ggplot2 >=2.2
    - r-gridextra
    - r-gtable
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-knitr
    - r-lattice
    - r-latticeextra
    - r-nnet
    - r-rmarkdown
    - r-rpart
    - r-survival >=3.1_6
    - r-viridis

test:
  commands:
    - $R -e "library('Hmisc')"           # [not win]
    - "\"%R%\" -e \"library('Hmisc')\""  # [win]

about:
  home: https://hbiostat.org/R/Hmisc/
  dev_url: https://github.com/harrelfe/Hmisc
  license: GPL-2.0-or-later
  summary: Contains many functions useful for data analysis, high-level graphics, utility operations, functions for computing sample size and power, importing and annotating datasets, imputing missing values, advanced table making, variable clustering, character string manipulation, conversion of R objects to LaTeX and html
    code, and recoding variables.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
