{% set version = "4.4-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hmisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Hmisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Hmisc/Hmisc_{{ version }}.tar.gz
  sha256: e6178e38f05670d531a06072f8aa88a49da101876252a5cf83f94db0a7c8a356

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-formula
    - r-acepack
    - r-base64enc
    - r-cluster
    - r-data.table
    - r-foreign
    - r-ggplot2 >=2.2
    - r-gridextra
    - r-gtable
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-lattice
    - r-latticeextra
    - r-nnet
    - r-rpart
    - r-survival >=2.40_1
    - r-viridis
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-formula
    - r-acepack
    - r-base64enc
    - r-cluster
    - r-data.table
    - r-foreign
    - r-ggplot2 >=2.2
    - r-gridextra
    - r-gtable
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-lattice
    - r-latticeextra
    - r-nnet
    - r-rpart
    - r-survival >=2.40_1
    - r-viridis

test:
  commands:
    - $R -e "library('Hmisc')"           # [not win]
    - "\"%R%\" -e \"library('Hmisc')\""  # [win]

about:
  home: http://biostat.mc.vanderbilt.edu/Hmisc, https://github.com/harrelfe/Hmisc
  license: GPL (>= 2)
  summary: Contains many functions useful for data analysis, high-level graphics, utility operations, functions for computing sample size and power, importing and annotating datasets, imputing missing values, advanced table making, variable clustering, character string manipulation, conversion of R objects to LaTeX and html
    code, and recoding variables.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: Hmisc
# Version: 4.2-0
# Date: 2019-01-25
# Title: Harrell Miscellaneous
# Author: Frank E Harrell Jr <f.harrell@vanderbilt.edu>, with contributions from Charles Dupont and many others.
# Maintainer: Frank E Harrell Jr <f.harrell@vanderbilt.edu>
# Depends: lattice, survival (>= 2.40-1), Formula, ggplot2 (>= 2.2)
# Imports: methods, latticeExtra, cluster, rpart, nnet, acepack, foreign, gtable, grid, gridExtra, data.table, htmlTable (>= 1.11.0), viridis, htmltools, base64enc
# Suggests: chron, rms, mice, tables, knitr, ff, ffbase, plotly (>= 4.5.6), rlang
# Description: Contains many functions useful for data analysis, high-level graphics, utility operations, functions for computing sample size and power, importing and annotating datasets, imputing missing values, advanced table making, variable clustering, character string manipulation, conversion of R objects to LaTeX and html code, and recoding variables.
# License: GPL (>= 2)
# LazyLoad: Yes
# URL: http://biostat.mc.vanderbilt.edu/Hmisc, https://github.com/harrelfe/Hmisc
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-01-25 22:28:42 UTC; harrelfe
# Repository: CRAN
# Date/Publication: 2019-01-26 23:20:03 UTC
