{% set version = '4.0-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hmisc
  version: {{ version|replace("-", "_") }}

source:
  fn: Hmisc_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/Hmisc_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/Hmisc/Hmisc_{{ version }}.tar.gz
  sha256: 5d395286d699bcabb6460c91798019d84b1cfa7a033841aa3ac5a02f4407e4fd

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-formula
    - r-acepack
    - r-base64enc
    - r-cluster
    - r-data.table
    - r-foreign
    - r-ggplot2 >=2.2
    - r-gridextra
    - r-gtable
    - r-htmltable
    - r-htmltools
    - r-lattice
    - r-latticeextra
    - r-nnet
    - r-rpart
    - r-survival >=2.40_1
    - r-viridis

  run:
    - r-base
    - r-formula
    - r-acepack
    - r-base64enc
    - r-cluster
    - r-data.table
    - r-foreign
    - r-ggplot2 >=2.2
    - r-gridextra
    - r-gtable
    - r-htmltable
    - r-htmltools
    - r-lattice
    - r-latticeextra
    - r-nnet
    - r-rpart
    - r-survival >=2.40_1
    - r-viridis

test:
  commands:
    - $R -e "library('Hmisc')"  # [not win]
    - "\"%R%\" -e \"library('Hmisc')\""  # [win]

about:
  home: http://biostat.mc.vanderbilt.edu/Hmisc, https://github.com/harrelfe/Hmisc
  license: GPL (>= 2)
  summary: Contains many functions useful for data analysis, high-level graphics, utility operations,
    functions for computing sample size and power, importing and annotating datasets,
    imputing missing values, advanced table making, variable clustering, character string
    manipulation, conversion of R objects to LaTeX and html code, and recoding variables.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
