appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: o+gKm+sqNGbw2m9sqQPp7WqmWuoTQ1RCOMHSKKbDNb/12aJ/kxnNrNZK73tvftPZcnR4UbHdBsAW3Yb7+pPOz1hnBe4nddZXHwy3WxP1yzzQyvcRyQ8+/K+61AsNpqg4+H9of9bnutDZRS8Ecn1/uyCist9Re0ap7gH+bORUy1uWxcojktd5OptnKArV4sCMIDolRetfUonzLwUxeH4Rv+YKNQLP8Lbctn/8sJzkk0q721Gbi1DbSrDXieIxOmtsndR/BBmU+CKnfhqbLjMZvo+gd81xpcpU4/X0+5zDG9JpPey0RyDvMIr4NnDBSIzLpI+XZ8GEr0ndtdkVjwhGyb/MAON1md3azzJ+9iVuV5jksXGw0T7qYPBpv5VEwHB8rxHOFssrtLh/gKiRfwL0Q0ej9mNwRg0fpYZhAi68eLwcWJ/1EpNqh5GDRAGlWET+3sfRIJZgIeXA602mZTUEbOdAyd8M828ZxbOllkzfiyqvRoDxftrUA+dUhjIEwbZw4nij8ziDIMVCXoB3UylobDG8ZN9yiXyTYBShnNWnYjbv0nbmwza8QtlGLkW8N1/35reMHiEZouVxlH03j9RQsdxJQZW2nDwcR1UtB96jo7uZQoqX1dzVCDaVJQ1ZkTAjBAtoEt4gA0HVPHfg4yV+RH5sevE5BpyDaBIqLKpqPRA=
